---

- name: Create systemd service
  ansible.builtin.template:
    src: java.service.j2
    dest: '/etc/systemd/system/{{ __java_service_name }}.service'
    owner: root
    group: root
    mode: '0755'

- name: Set autostart on boot and run daemon-reload
  ansible.builtin.systemd_service:
    name: '{{ __java_service_name }}.service'
    daemon_reload: true
    enabled: true
