---

- name: Allow tcp ports
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  loop: '{{ allowed_tcp_ports }}'

- name: Enable ufw
  community.general.ufw:
    state: enabled
